[package]
description = "Fetching hash-addressed content."
homepage = "http://parity.io"
license = "GPL-3.0"
name = "parity-hash-fetch"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
log = "0.4"
mime = "0.3"
mime_guess = "2.0.0-alpha.2"
rand = "0.6"
rustc-hex = "1.0"
fetch = { path = "../../util/fetch" }
parity-bytes = "0.1"
ethereum-types = { git = "https://github.com/ordian/parity-common" }
parity-runtime = { path = "../../util/runtime" }
keccak-hash = { git = "https://github.com/ordian/parity-common" }
registrar = { path = "../../util/registrar" }

ethabi = { git = "https://github.com/ordian/ethabi" }
ethabi-derive = { git = "https://github.com/ordian/ethabi" }
ethabi-contract = { git = "https://github.com/ordian/ethabi" }

[dev-dependencies]
parking_lot = "0.7"
fake-fetch = { path = "../../util/fake-fetch" }
