[package]
description = "Ethcore stratum lib"
name = "ethcore-stratum"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = { git = "https://github.com/ordian/parity-common" }
keccak-hash = { git = "https://github.com/ordian/parity-common" }
jsonrpc-core = "10.0.1"
jsonrpc-tcp-server = "10.0.1"
log = "0.4"
parking_lot = "0.7"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"
tokio-io = "0.1"
